### ISSUE TITLE
Issue with recent update

### ISSUE THREAD

**Issue by rhysss-rice** [CorgiTaco-MC/CorgiLib#64]
Hi, I'm not sure if this was reported earlier or not but I'm having issues with the recent CorgiLib update, I keep getting this error:

`Caused by 0: java.lang.NoClassDefFoundError: corgitaco/corgilib/shadow/blue/endless/jankson/api/SyntaxError`

I installed the previous version and it works as normal so I guess I'll stick with that one for now.

**Comment by ScoutTheSaneless** [comment]
here's my crashlog in my pack to further support this report: https://mclo.gs/b1LsjIz

**Comment by JetVolcano** [comment]
Same here: https://mclo.gs/3riMqfu

**Comment by Silvertide7** [comment]
Yup, same here. 1.21.1 neoforge latest update:
Stacktrace:
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
-- Mod loading issue --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: corgitaco/corgilib/shadow/blue/endless/jankson/api/SyntaxError

**Comment by rsp4jack** [comment]
Downgrade CorgiLib to 5.0.0.4 works for me.

**Comment by IsaacAMurray** [comment]
Hello, I also had this issue with the latest version. I had to rollback to the version just before.

**Comment by Silvertide7** [comment]
Yeah it's not a big deal, I'm just on the old version for now. Just wanted to post for an eventual fix, especially if dependent mods require the new version at some point.

**Comment by Klouver-github** [comment]
i want a refund on this mod i paid for! I spent 25.99 including shipping and handling

**Comment by JetVolcano** [comment]
> i want a refund on this mod i paid for! I spent 25.99 including shipping and handling

What?

**Comment by CorgiTaco** [comment]
Should be resolved as of 5.0.0.6

**Comment by IchHabeHunger54** [comment]
Hate to say this, but still present, at least on Neo 5.0.0.6.

**Comment by rhysss-rice** [comment]
yeah i still got the same error

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/d3d8e7ea-5d55-4439-a5aa-4f36f1d1685c" />

**Comment by agentwolf88** [comment]
Still not work. Downgrade to 5.0.0.4 works.

**Comment by CorgiTaco** [comment]
should NOW be fixed on all Modloaders according to @JT122406
